target 'Jewelry' do
	platform:ios, '6.1'

    #pod 'FEFramework', '0.0.1'
    pod 'FEFramework', :path => '../../FEFramework'
	#pod 'FEFramework',:git => 'git@github.com:FerrariXX/FEFramework.git'
    pod "SDWebImage",               '3.6.0'  #"SDWebImage/WebP"
    pod "AFNetworking",             '1.3.3'
    pod "ICViewPager"                   #min ios6.1
    pod "SVPullToRefresh"
end
